
# --- Datasource MySQL ---
spring.application.name=StreamLab-Api
spring.datasource.url=jdbc:mysql://localhost:3306/streamlab
spring.datasource.username=vasile_streamlab
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- Server ---
server.port=8080

# --- JWT ---
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

spring.jackson.deserialize.fail-on-unknown-properties=true



