name: Deploy StreamLab-Api

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Build e riavvio container
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          docker compose up -d --build